/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesAmlTransactionMonitoringRouteImport } from './routes/guides.aml-transaction-monitoring'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAmlTransactionMonitoringRoute =
  GuidesAmlTransactionMonitoringRouteImport.update({
    id: '/guides/aml-transaction-monitoring',
    path: '/guides/aml-transaction-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/aml-transaction-monitoring': typeof GuidesAmlTransactionMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/aml-transaction-monitoring': typeof GuidesAmlTransactionMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/aml-transaction-monitoring': typeof GuidesAmlTransactionMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/guides/aml-transaction-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/guides/aml-transaction-monitoring'
  id: '__root__' | '/' | '/sitemap.xml' | '/guides/aml-transaction-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesAmlTransactionMonitoringRoute: typeof GuidesAmlTransactionMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/aml-transaction-monitoring': {
      id: '/guides/aml-transaction-monitoring'
      path: '/guides/aml-transaction-monitoring'
      fullPath: '/guides/aml-transaction-monitoring'
      preLoaderRoute: typeof GuidesAmlTransactionMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesAmlTransactionMonitoringRoute: GuidesAmlTransactionMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
